version: '2'
services:
  customer-mysql:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
      - MYSQL_DATABASE=customer_db
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    ports:
      - 3306:3306